### ISSUE TITLE
Overview dashboard

### ISSUE THREAD

**Issue by ghost** [localstack/localstack-python-client#18]
Hi,
is it possible to expose the web_ui in [config.py?](https://github.com/localstack/localstack-python-client/blob/master/localstack_client/config.py)

`'dashboard': '{proto}://{host}:8080',`

I am not sure if that's the right way. If yes I could just do a PR.

**Comment by whummer** [comment]
Thanks for this suggestion @8bitmac - added in version `0.13`. Note, however, that the port configuration for the Web UI is currently handled slightly differentlly. We would still need to adjust it in the main LocalStack repo, to make the web UI port configurable analogous to the other services.
