### ISSUE TITLE
Possible to have multiple and different sessions?

### ISSUE THREAD

**Issue by rpattcorner** [localstack/localstack-python-client#22]
Also related to the latest comment on [1498 ](https://github.com/localstack/localstack/issues/1498)in the main localstack repo.

I'm starting multiple localstack instances using the new EDGE_PORT capability with a different edge port for each localstack instance in an effort to mock multiaccount environments per your suggestion in the localstack issue above.

Is it currently possible to configure a localstack-python-client session to point at one specific instance of localstack (representing one AWS account) versus the another (representing another account)?  It doesn't look like it from a look thru the code, but if there is, could I trouble you to point it out?

If not, that would be a great feature, very close to multi-account capability.  Many applications are working in multi-account environments since the advent of organizations, mine included.

I suppose it might be possible to address this use case at the session client level instead, using the old port per service capability, but it sounds like EDGE_PORT is the way of the future.

**Comment by alexrashed** [comment]
Hi @rpattcorner!
Sorry for the incredibly late answer on the ticket. As mentioned in https://github.com/localstack/localstack/issues/1498, LocalStack is designed to run on a single endpoint for now. But it now fully supportss multi-accounts, and multi-region.
I'll close this issue for now. Please let me know if there are any open questions, then I'll be happy to reopen this one, or discuss it in a new issue. Thanks!
