### ISSUE TITLE
localstack supports unique port 4566 now.

### ISSUE THREAD

**Issue by ozbillwang** [localstack/localstack-python-client#24]
https://github.com/localstack/localstack#announcements

* **2020-09-15**: A major (breaking) change has been merged in PR #2905 - starting with releases after `v0.11.5`, all services are now exposed via the edge service (port 4566) only! Please update your client configurations to use this new endpoint.

So all below ports can be changed to `4566`

https://github.com/localstack/localstack-python-client/blob/master/localstack_client/config.py#L12-L79

Or maybe you can simplify the code directly

**Comment by whummer** [comment]
Thanks for bringing this to our attention. We have already disabled the service specific ports here:

https://github.com/localstack/localstack-python-client/blob/master/localstack_client/config.py#L89-L93

An environment variable `USE_LEGACY_PORTS` has been added to utilize the old/legacy ports. As part of our ongoing refactoring, this code may get removed in a future release of the LocalStack Python client. Thanks
