### ISSUE TITLE
Suggestion: document environment variable LOCALSTACK_HOST

### ISSUE THREAD

**Issue by raffienficiaud** [localstack/localstack-python-client#26]
I am using Celery w. dynamoDB backend. The way to configure the dynDB endpoint in Celery is intercepted by localstack and  `localhost` is injected instead. 

Reading the code, I've found the environment variable `LOCALSTACK_HOST` that can be used for this purpose, I believe it is worth mentioning that variable somewhere in the README.

**Comment by florianakos** [comment]
A year ago I also discovered this option to change the HOST via that variable, but only after reading through the source code! I definitely agree that it should be better documented!

**Comment by AndrewFarley** [comment]
Note: Fixed in #44 :)

**Comment by alexrashed** [comment]
Seems like this one is already fixed. I'll close this issue for now.
