### ISSUE TITLE
Proper way to use mock client in local environment

### ISSUE THREAD

**Issue by sfdye** [localstack/localstack-python-client#6]
Is there a recommended way to use this library when I am in the local environment, while using boto3 for production? aka. for the same piece of code, do I need a logic to detect the current environment and use different client for different environment, or is there a better way to do it?

**Comment by whummer** [comment]
Thanks for reporting @sfdye . Indeed, we do have an environment abstraction in the main LocalStack repository ([see here](https://github.com/localstack/localstack/blob/master/localstack/utils/aws/aws_stack.py#L36-L106)), but this code still needs to be ported over to this repository.

Essentially, you can use the environment variable `ENV` to specify the target environment in which resources should be deployed. The format for `ENV` is `<region>:<prefix>`, where `<region>` is an AWS region specifier (e.g., `us-east-1`) and `<prefix>` is an arbitrary string (the prefix is currently not used in LocalStack, but needed for compatibility with some legacy applications).

For example, if you start your application by setting `ENV` to `us-east-1:prod`, LocalStack will use the AWS region `us-east-1`, using the standard boto3 credentials lookup mechanism.
```
ENV=us-east-1:prod python main.py
```

Hope that helps.

**Comment by sfdye** [comment]
@whummer Thanks for the reply! But I am still not very sure what you meant.

Just to give some background, I am using django and have these two environments: `local` and `prod`. What I want (and I think the correct use case) is that, when I am in the local environment,  the localstack-python-client will be used; when I am in the production environment, the actual boto3 client will be used. How can I achieve this elegantly? I wan to write only one set of code that will work for both environments with only changing maybe the environment variables.

My current approach is:
```python
sqs = boto3.client(
    'sqs',
    endpoint_url=settings.AWS_ENDPOINT_URL,
    region_name=settings.AWS_DEFAULT_REGION
)
``` 
and in my local settings:
```python
AWS_ENDPOINT_URL = 'http://localstack:4576'
```

However, with this approach I could not construct the endpoint url for production? Or do you mean I can use the following for both `local` and `prod`:

```python
import localstack_client.session

session = localstack_client.session.Session()
sqs = session.client('sqs')
```
and specify a `ENV` environment variable for `prod` (say `ap-southeast-1:prod`), and this piece of code will work for both environments?

**Comment by whummer** [comment]
This issue is outdated, the `ENV` variable is deprecated. The recommended way is to create a small custom client factory which creates boto/localstack clients, depending on prod or test mode. There might also be some libraries out there which can achieve this task.

**Comment by MoBattah** [comment]
^^ That's not a very good solution.
